ezsystems/ez-support-tools

.travis.yml, Command/SystemInfoDumpCommand.php, EzSystemsEzSupportToolsBundle.php, Resources/config/services.yml, SystemInfo/Collector/EzcHardwareSystemInfoCollector.php, SystemInfo/Collector/SystemInfoCollector.php, SystemInfo/EzcSystemInfoFactory.php, SystemInfo/Value/HardwareSystemInfo.php, SystemInfo/Value/SystemInfo.php, Tests/SystemInfo/Collector/EzcHardwareTest.php, Tests/bootstrap.php, composer.json, phpunit.xml
> Fixes https://jira.ez.no/browse/EZP-25490
Implements the EzcHardware info collector only (split out from EzcSystem info for compartmentalisation reasons) to verify architecture and naming, and a simple, temporary Command:
```console
php app/console ez-support-tools:dump-info support_tools.info_collectors.ezc_hardware
array (
'cpuType' => 'Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz',
'cpuSpeed' => 2591.9000000000001,
'cpuCount' => 1,
'memorySize' => 1554632704,
)
```
=> Fix EZP-25490: Reimplement SystemInfo in ez-support-tools

SystemInfo/Collector/EzcHardwareSystemInfoCollector.php, Tests/SystemInfo/Collector/EzcHardwareSystemInfoCollectorTest.php
> Fixes https://jira.ez.no/browse/EZP-25567
> Status: Ready to review
=> Fix EZP-25567: eZSupportTools HardwareSystemInfoCollector minor fixes

Resources/config/services.yml
> Fixes https://jira.ez.no/browse/EZP-25580
The service is named `support_tools.info_collectors.php`, but to be consistent with the class name and the hardware collector it should be named `support_tools.info_collectors.ezc_php`, as it uses the Components.
=> Fix EZP-25580: eZSupportTools PHP collector service naming fix

Command/SystemInfoDumpCommand.php, SystemInfo/Collector/DoctrineDatabaseSystemInfoCollector.php, SystemInfo/Collector/EzcHardwareSystemInfoCollector.php, SystemInfo/Collector/EzcPhpSystemInfoCollector.php, SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php, SystemInfo/Collector/SystemInfoCollector.php, Tests/SystemInfo/Collector/DoctrineDatabaseSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/EzcHardwareSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/EzcPhpSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php
> Fixes https://jira.ez.no/browse/EZP-25607
Rename `SystemInfoCollector::build()` to `collect()`.
=> Fix EZP-25607: eZSupportTools infocollector naming fix

Controller/SystemInfoController.php, DependencyInjection/Compiler/ViewBuilderPass.php, EzSystemsEzSupportToolsBundle.php, Resources/config/routing.yml, Resources/config/services.yml, Resources/config/view.yml, Tests/View/Matcher/SystemInfo/IdentitifierTest.php, Tests/View/SystemInfoViewBuilderTest.php, View/Matcher/SystemInfo/Identifier.php, View/SystemInfoView.php, View/SystemInfoViewBuilder.php
> https://jira.ez.no/browse/EZP-25579
> Working prototype, with all the hard requirements
> PlatformUI integration: https://github.com/ezsystems/PlatformUIBundle/pull/532
> ezplatform integration: https://github.com/ezsystems/ezplatform/compare/ezp25579-view_api_integration
- `SystemInfoViewController` + `viewInfoAction`
- `/ez-support-tools/view/info/{identifier}` route. Identifier is the name of the class minus SystemInfo, underscorized: `PhpSystemInfo` :arrow_right: `php`
- `SystemInfoView` object + builder
- `SystemInfo\Identifier` view matcher
`/ez-support-tools/view/php` matches the SystemInfoController view action.
The template (property of the view) used to render the SystemInfoView is set depending on the view matchers configuration.
The template used by each info type can be …
=> EZP-25579: SystemInfo view

DependencyInjection/EzSystemsEzSupportToolsExtension.php, Resources/config/default_settings.yml
Avoids this error:
```
[eZ\Publish\Core\MVC\Exception\ParameterNotFoundException]
Parameter 'system_info_view' with namespace '' could not be found.
```
=> Added default system_info_view settings

Tests/View/SystemInfoViewBuilderTest.php, View/SystemInfoViewBuilder.php
Allows custom viewType usage:
```twig
{{ render( 
controller( 
"support_tools.view.controller:viewInfoAction",
{ "systemInfoIdentifier": "php", "viewType": "custom_view" } 
) 
) }}
```
=> Made the builder pass the viewType to the SystemInfoView

.travis.yml, Command/SystemInfoDumpCommand.php, DependencyInjection/Compiler/SystemInfoCollectorPass.php, EzSystemsEzSupportToolsBundle.php, Resources/config/services.yml, Resources/config/view.yml, SystemInfo/Registry/IdentifierBased.php, SystemInfo/SystemInfoCollectorRegistry.php, Tests/SystemInfo/Registry/IdentifierBasedTest.php, Tests/View/SystemInfoViewBuilderTest.php, View/SystemInfoViewBuilder.php, composer.json
> Implements https://jira.ez.no/browse/EZP-25598
This does not implement infocollector descriptions, that's not needed/important (at least for now).
=> Fix EZP-25598: eZSupportTools infocollector registry

Resources/config/routing.yml
> Fixing issue found in https://jira.ez.no/browse/EZP-25653
> See also: ezplatform PR: https://github.com/ezsystems/ezplatform/pull/106
The system_info_view route is not used, and has no access control, this removes it.
=> Remove unused system_info_view route

composer.json
This PR allows `ezpublish-kernel:^7.0@dev` for `ez-support-tools`.
Reason: Right now we have to make workaround to install `ezplatform:2.0` meta-repository dependencies by setting requirement for `ezpublish-kernel` in the form of `7.0.x-dev as 6.99.x-dev` instead of simply `^7.0@dev`. This change solves that partially (see also: ezsystems/ezplatform-http-cache#16).
=> [Composer] Allowed ezpublish-kernel ^7.0

.gitignore, .php_cs, .travis.yml, Command/SystemInfoDumpCommand.php, DependencyInjection/EzSystemsEzSupportToolsExtension.php, SystemInfo/Collector/DoctrineDatabaseSystemInfoCollector.php, SystemInfo/Collector/EzcHardwareSystemInfoCollector.php, SystemInfo/Collector/EzcPhpSystemInfoCollector.php, SystemInfo/EzcSystemInfoWrapper.php, SystemInfo/OutputFormat.php, SystemInfo/OutputFormat/JsonOutputFormat.php, SystemInfo/OutputFormatRegistry.php, SystemInfo/Registry/IdentifierBased.php, Tests/SystemInfo/Collector/DoctrineDatabaseSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/EzcPhpSystemInfoCollectorTest.php, Tests/View/SystemInfoViewBuilderTest.php, View/SystemInfoViewBuilder.php, composer.json
This PR introduces `.php_cs` config and aligns CS.
To simplify fixing code it adds dev dependency on `php-cs-fixer` and introduces composer command:
```
composer fix-cs
```
which runs fixer on all files.
**TODO**:
=> EZP-28161: Enable php-cs-fixer aligned with v2.7.1 settings

SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php
When using Composer path repositories, `time` and `source` are not present in package data, which crashes rendering.
=> Fix undefined index notice when using path repos

.travis.yml, Tests/SystemInfo/Collector/ConfigurationSymfonyKernelSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/DoctrineDatabaseSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/EzcHardwareSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/EzcPhpSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php, Tests/SystemInfo/Registry/IdentifierBasedTest.php, Tests/View/Matcher/SystemInfo/IdentitifierTest.php, Tests/View/SystemInfoViewBuilderTest.php, View/Matcher/SystemInfo/Identifier.php, composer.json
Some cleanup here too in order to align with other repos.
=> [Travis] Fix tests, move to newer version of phpunit

Resources/config/services.yml
JIRA: https://jira.ez.no/browse/EZP-30262
The generated link has form:
https://doc.ezplatform.com/en/#2.5/getting_started/install_ez_enterprise/
but all our current doc links do not have the hashtag, for example:
https://doc.ezplatform.com/en/2.4/getting_started/install_ez_enterprise/
https://doc.ezplatform.com/en/2.3/getting_started/install_ez_enterprise/
2.5 doc will also be published without the `#`.
=> Updated install_ee doc link

Resources/views/themes/admin/dashboard/block/ez.html.twig
The URL is defined as `update`in https://github.com/ezsystems/ez-support-tools/blob/1.0/Resources/config/services.yml#L27
This problem occurred on current master in https://github.com/ezsystems/ezplatform/pull/397 in tests, when browsing the Dashboard:
https://res.cloudinary.com/ezplatformtravis/image/upload/v1556274925/screenshots/5cc2deed9682e714913640-vendor_ezsystems_ezplatform-admin-ui_features_objectstates_feature_11_zzymim.png
=> Use correct key for update url

.travis.yml, AdminUi/Component/EzInfoTwigComponent.php, Resources/config/services.yml, Resources/views/themes/admin/dashboard/block/ez.html.twig, SystemInfo/Collector/EzSystemInfoCollector.php, SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php, SystemInfo/Exception/ComposerJsonFileNotFoundException.php, SystemInfo/Exception/ComposerLockFileNotFoundException.php, SystemInfo/Value/ComposerSystemInfo.php, Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/_fixtures/composer.json
Adds logic to also read info from composer.json to detect if packages are pulled from ttl channel
or not.
Besides the current issues with updates.ez.no telling composer the packages are ttl when they are not (diff between packages.json and composer.json). This also solves issues when people switch from TTL to BUL, and install won't show they have switched until all TTL packages actually have a new release to pull in.
=> EZP-30402: Make Dashboard code more solid when it comes to detecting trial or not

Resources/views/themes/admin/dashboard/block/ez.html.twig
> JIRA: https://jira.ez.no/browse/EZP-30814
Continuation of https://github.com/ezsystems/ezpublish-kernel/pull/2708: replaced `spaceless` tag usages in favour of `spaceless` filter
=> EZP-30814: Removed Twig deprecations

Resources/translations/dashboard.en.xlf, Resources/views/themes/admin/dashboard/block/ez.html.twig, SystemInfo/Collector/EzSystemInfoCollector.php, SystemInfo/Value/EzSystemInfo.php
Does:
- Always show dev message if in dev, even if in debug mode, so Engineering Sprint demos won't show `Trial` badge
- Change the message to be more concrete to make it hopefully more clear what user needs to do to fix it
=> Improve dev message on dashboard, and always show when in dev

SystemInfo/Collector/EzSystemInfoCollector.php, composer.json
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31007](https://jira.ez.no/browse/EZP-31007)
| **Requires** | ezsystems/ezplatform-core#16
| **Target version** | `2.0` for eZ Platform `v3.0`
| **BC breaks**      | no
Due to ezsystems/ezplatform#510, explained in ezsystems/ezplatform-core#16.
=> EZP-31007: Changed eZ Platform version detection

SystemInfo/Collector/EzSystemInfoCollector.php, Tests/SystemInfo/Collector/EzSystemInfoCollectorTest.php
This is a follow up to [EZP-31007](https://jira.ez.no/browse/EZP-31007) via #47 
When working on #47, in reference to `ezplatform-kernel` package being gone, I've missed the fact that `$ez->release` is needed in the `X.Y` format to detect EOM & EOL state.
It results in a following incorrect message on the AdminUI Dasboard:
_This requires more work to be future-proof. The PR provides minimum reasonable fix along with missing test coverage. The point of test coverage, while not testing directly processing of version number, was to detect any parsing errors in the future. Right now there's no point testing EOM/EOL detection as this will definitely fail in the future because the dates are hardcoded._
=> Fixed eZ Platform EOM/EOL detection

SystemInfo/Collector/EzSystemInfoCollector.php
https://jira.ez.no/browse/EZP-31719
Updated release, EOM and EOL dates based on 3.0 tag date and https://support.ez.no/Public/Service-Life
The 3.0 life cycle has been squashed here a lot compared to how it was. Suggestions? If we agree to extend it, I will update https://support.ez.no/Public/Service-Life too.
Need to fix the HTML showing up in the alert box too, but that's in admin-ui repo.
PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1421
=> EZP-31719: Incorrect end of life information on Dashboard

Resources/translations/dashboard.en.xlf, Resources/views/themes/admin/dashboard/block/ez.html.twig
> JIRA: https://jira.ez.no/browse/EZP-31719
Backport of ezsystems/ezplatform-admin-ui#1421 for eZ Platform 2.5.
=> EZP-31719: Verbatim HTML in end of life information on Dashboard

Command/SystemInfoDumpCommand.php
Symfony 5 commands need to return an exit code that is currently missing. Due to that, the command results in error in eZ Platform 3.1:
```Return value of "EzSystems\EzSupportToolsBundle\Command\SystemInfoDumpCommand::execute()" must be of the type int, "null" returned.```
=> Missing success code for the SystemInfoDumpCommand

src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
After moving system information UI components there were some missing changes from [PR introducing new design for notifications and alerts](https://github.com/ezsystems/ezplatform-admin-ui/pull/1555/files#diff-2194259bc79abc5ffc127723d085ee1b21fb0a1638a3b9bfcedba55c9a77cf0f). This PR aims to fix that.
=> EZP-32027: Broken design for system information alert and tab

composer.json, src/lib/EventListener/ConfigureMainMenuListener.php
Excerpt from JIRA:
>System information tab should be moved from MainMenuBuilder.php to the dedicated listener within ez-support-tools to be aligned with other bundles practices.
Related to: https://github.com/ezsystems/ezplatform-admin-ui/pull/1596
=> EZP-32038: Move System information tab to ez-support-tools

src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
Update 3.1/3.2/3.3 release dates in v3.2+
- Correct 3.1 dates to what's already set in that branch
- Update 3.2 dates based on 4 months maintenance and 2 months security
- Add 3.3 dates, also 4 + 2
=> Update/correct 3.1/3.2/3.3 dates

Command/SystemInfoDumpCommand.php
Forward compatibility, as we often instructs customer to run this, and don't always know which version they are on (upgrades and so on.)
This also simplify instructions for how to dump info about the system.
=> [DX] Setup short forward compatible 'ibexa:info' aliases for system info dump command

composer.json, src/bundle/DependencyInjection/EzSystemsEzSupportToolsExtension.php, src/bundle/Resources/config/services.yaml, src/bundle/Resources/config/view.yaml, src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php, src/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php, src/bundle/SystemInfo/Value/IbexaSystemInfo.php, src/bundle/Tests/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php
This PR takes a portion of #77 changes without `subscription.json` fetch and making this package a composer plugin.
The changes aim to fix Product name & release detection for Ibexa DXP 3.3.
- Product name & version on the Dasboard (should be 3.3.0-dev)
- Admin -> System info -> My ibexa tab (only dates were changed)
- "Powered by HTTP" header
=> EZP-32257: Prepared Product name and release detection for Ibexa DXP 3.3

src/bundle/Command/SystemInfoDumpCommand.php
> JIRA: [EZP-32259](https://jira.ez.no/browse/EZP-32259)
Requires https://github.com/ezsystems/ezplatform-kernel/pull/153. New command name is **ibexa:system-info:dump**. Aliases introduced in #74 are still available.
=> EZP-32259: Replaced "ezplatform" commands namespace with "ibexa"

src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EC-333](https://issues.ibexa.co/browse/EC-333)
| **Type**                                   | bug
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | yes
| **Doc needed**                       | no
As of today `ezcommerce-admin-ui` is also a part of Ibexa Content, so we need to align with that here and detect Commerce edition based on `ezcommerce-transaction` package.
=> EC-333: Based Commerce detection on ezcommerce-transaction package

src/bundle/Resources/config/services.yaml, src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php, src/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php, src/bundle/SystemInfo/Value/IbexaSystemInfo.php, src/bundle/Tests/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php, src/bundle/Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php, src/lib/Tests/VersionStability/VersionStabilityCheckerTest.php, src/lib/Value/Stability.php, src/lib/VersionStability/ComposerVersionStabilityChecker.php, src/lib/VersionStability/VersionStabilityChecker.php
https://issues.ibexa.co/browse/EZP-32307
This PR provides implemented `VersionStabilityChecker` for displaying valid version stability. Since `Ibexa/website-skeleton` (https://github.com/ibexa/website-skeleton/blob/main/composer.json#L6) provides `minimum-stability` set to `dev` all versions are marked as ‘`dev`’. Now version stability is based on `ibexa/oss` version because this package is installed for all Ibexa Platform versions. For BC break reason old check based on composer.lock minimum stability is set as callback in case when Ibexa/oss is not found.
=> EZP-32307: Fixed check version stability

src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
Actual release date, and service life dates taken from master. Are these correct?
Reminder to self, update https://support.ibexa.co/Public/Service-Life when approved, it has no 3.3 dates yet.
=> Correct 3.3 release/maintenance dates

Resources/translations/dashboard.en.xlf, Resources/views/themes/admin/dashboard/block/ez.html.twig, SystemInfo/Collector/EzSystemInfoCollector.php, SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php, SystemInfo/Exception/ComposerFileValidationException.php, SystemInfo/Exception/ComposerJsonFileNotFoundException.php, SystemInfo/Exception/ComposerLockFileNotFoundException.php, SystemInfo/Exception/SystemInfoException.php, SystemInfo/Value/InvalidSystemInfo.php, Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/_fixtures/corrupted_composer.json, Tests/SystemInfo/Collector/_fixtures/corrupted_composer.lock, View/SystemInfoViewBuilder.php, composer.json
JIRA ticket: [IBX-385](https://issues.ibexa.co/browse/IBX-385)
>Currently, whenever composer.json or composer.lock files get accidentally corrupted, the system will return exceptions coming from ez-support-tools (where those files are parsed) which results in the system being unusable. The idea is to show some warnings in:
>- the dashboard,
> - the System Information tab,
> - ez-support-tools:dump-info
>if the composer files are either not accessible or don't contain valid data.
Depends on https://github.com/ezsystems/ezplatform-admin-ui/pull/1758.
TODO:
//edit not sure to what I owe ezrobot's endorsement... 😄
=> IBX-385: Fixed error handling when composer files are corrupted

src/bundle/Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php
The test flaw introduced in: https://github.com/ezsystems/ez-support-tools/commit/d2b375038c586f6cc863587030268248035e8712.
=> IBX-385: Fixed tests failing after merge-up

src/bundle/Resources/views/themes/admin/system_info/my_ibexa.html.twig, src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
JIRA: [IBX-422](https://issues.ibexa.co/browse/IBX-422)
Icons should be rebranded from ez to ibexa.
Main PR: https://github.com/ezsystems/ezplatform-page-builder/pull/760
=> IBX-422: As a Maintainer, I want to have rebranded icons

src/bundle/Resources/views/themes/admin/system_info/info.html.twig, src/bundle/Resources/views/themes/admin/ui/tab/system_info.html.twig
JIRA: https://issues.ibexa.co/browse/IBX-497
main PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1780
=> IBX-497: Redesign tabs for 4.0

src/lib/Tests/VersionStability/VersionStabilityCheckerTest.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31560](https://issues.ibexa.co/browse/EZP-31560)
| **Type**                                   | bug
| **Target Ibexa version** | `v3.3` - please update `x` accordingly
| **BC breaks**                          | no
Class `EzSystems\EzSupportTools\VersionStability\VersionStabilityCheckerTest` located in `./src/lib/Tests/VersionStability/VersionStabilityCheckerTest.php` does not comply with psr-4 autoloading standard. 
Introduced in #86 and missed by accident.
- ~Provided automated test coverage.~ // na
=> EZP-31560: Fixed VersionStabilityCheckerTest class file path
