ezsystems/ez-support-tools

Resources/config/services.yml, SystemInfo/Collector/EzcPhpSystemInfoCollector.php, SystemInfo/Value/PhpSystemInfo.php, Tests/SystemInfo/Collector/EzcPhpSystemInfoCollectorTest.php
> Implements https://jira.ez.no/browse/EZP-25564, subtask of https://jira.ez.no/browse/EZP-25563
Collects information about PHP version and accelerator.
=> Fix EZP-25564: Reimplement PHP system info collector

Resources/config/services.yml, SystemInfo/Collector/DoctrineDatabaseSystemInfoCollector.php, SystemInfo/Value/DatabaseSystemInfo.php, Tests/SystemInfo/Collector/DoctrineDatabaseSystemInfoCollectorTest.php
> Implements https://jira.ez.no/browse/EZP-25565, subtask of https://jira.ez.no/browse/EZP-25563
Collects information about the database in use.
=> Fix EZP-25565: Reimplement database system info collector

Resources/config/services.yml, SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php, SystemInfo/Exception/ComposerLockFileNotFoundException.php, SystemInfo/Value/ComposerPackage.php, SystemInfo/Value/ComposerSystemInfo.php, Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php, Tests/SystemInfo/Collector/_fixtures/composer.lock
> Implements https://jira.ez.no/browse/EZP-25566, subtask of https://jira.ez.no/browse/EZP-25563
Collects information about installed Composer packages.
=> Fix EZP-25566: Composer packages system info collector

Resources/config/services.yml, SystemInfo/Collector/ConfigurationSymfonyKernelSystemInfoCollector.php, SystemInfo/Value/SymfonyKernelSystemInfo.php, Tests/SystemInfo/Collector/ConfigurationSymfonyKernelSystemInfoCollectorTest.php
> Implements https://jira.ez.no/browse/EZP-25599
Collects all Symfony kernel parameters.
=> Fix EZP-25599: Symfony kernel system info collector

Resources/config/services.yml, Resources/config/view.yml, phpunit.xml
JIRA Story: [EZP-26128](https://jira.ez.no/browse/EZP-26128)
**TODO**:
=> EZP-26128: As a Developer I want deprecation issues resolved, so that application logs are clean

Resources/config/services.yml
> Fixes https://jira.ez.no/browse/EZP-26391
> Ready for review
It's not the factory that's lazy, but the service it builds.
=> EZP-26391: ez-support-tools factory called on every request

Command/SystemInfoDumpCommand.php, DependencyInjection/Compiler/OutputFormatPass.php, DependencyInjection/Compiler/SystemInfoOutputFormatPass.php, EzSystemsEzSupportToolsBundle.php, Resources/config/services.yml, SystemInfo/OutputFormat.php, SystemInfo/OutputFormat/JsonOutputFormat.php, SystemInfo/OutputFormatRegistry.php
JIRA: https://jira.ez.no/browse/EZP-26549
Implementation of JSON systeminfo output format using tagged services.
Replaces https://github.com/ezsystems/ez-support-tools/pull/18
=> EZP-26549: Output pretty JSON in dump-info command

Resources/views/themes/admin/dashboard/block/ez.html.twig
JIRA: https://jira.ez.no/browse/EZP-30221
=> EZP-30221: Trial/GPL info panel opening is laggy

Tests/SystemInfo/Collector/_fixtures/composer.json
=> EZEE-2800: Updated name of scssphp lib

Resources/config/view.yml
> JIRA: https://jira.ez.no/browse/EZP-30880
> Requires: https://github.com/ezsystems/ezpublish-kernel/pull/2745
=> EZP-30880: Aligned MatcherFactory service definition with Kernel changes

Resources/views/themes/admin/dashboard/block/ez.html.twig
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31148
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
Changed custom badge class to one from admin-ui.
https://github.com/ezsystems/ezplatform-admin-ui/pull/1172
=> EZP-31148: Changed custom badge class to admin-ui

Tests/SystemInfo/Collector/_fixtures/composer.json
**Jira ticket:** https://jira.ez.no/browse/EZP-31414
=> EZP-31414: As a Maintainer, I want to remove ezplatform-admin-ui-modules package

Resources/config/view.yml
> JIRA: https://jira.ez.no/browse/EZP-30543
=> EZP-30543: Removed Dynamic Settings functionality from kernel

SystemInfo/Collector/EzSystemInfoCollector.php
=> Update v3.1 release/lifetime dates

src/bundle/Resources/views/themes/admin/ui/tab/system_info.html.twig
JIRA: https://jira.ez.no/browse/EZP-32027
Background and margins in the `System information` tab were not entirely updated.
=> EZP-32027: Not updated design for system information tab

src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
jira ref: https://jira.ez.no/browse/EZP-32007
=> EZP-32007: change icons form #information to #system-information for dashboard alert

src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
jira ref: https://jira.ez.no/browse/EZP-32050
=> EZP-32050: design fixes dashboard

src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
JIRA ref: https://jira.ez.no/browse/EZP-32078
=> EZP-32078: Update icon path

.travis.yml, .travis/prepare_ezplatform.sh, composer.json
Things done:
1) Added a simple Behat job running the tests covering System Information part.
2) Split the current setup into two separate jobs: CS and unit tests
3) Added Slack notifications
~~Requires https://github.com/ezsystems/ezplatform-admin-ui/pull/1647 to be merged first.~~
=> [Travis] Added Behat job

composer.json, src/bundle/View/Matcher/SystemInfo/Identifier.php
> JIRA: https://issues.ibexa.co/browse/EZP-32221
=> EZP-32221: Removed dependency on outdated doctrine/inflector

src/bundle/DependencyInjection/EzSystemsEzSupportToolsExtension.php
Added configuration for extraction of translations to simplify the process of extracting translations
=> Added configuration for extraction of translations

src/bundle/Resources/translations/dashboard.en.xliff, src/bundle/Resources/translations/menu.en.xliff, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/translations/systeminfo.en.xliff
https://github.com/ezsystems/ezplatform-admin-ui/pull/1685
=> Added missing translation files

src/bundle/Resources/views/themes/admin/system_info/info.html.twig
jira ref: https://issues.ibexa.co/browse/EZP-32179
=> EZP-32179: Add footer to platform when user is logged in

src/bundle/Resources/translations/systeminfo.en.xliff
Those are changes after executing translation extraction
=> Updated translations

dependencies.json, src/bundle/Resources/views/themes/admin/system_info/info.html.twig
jira ref: https://issues.ibexa.co/browse/IBX-397
=> IBX-397: Redesign main layout

.travis.yml
JIRA: https://issues.ibexa.co/browse/IBX-264
Requires:
https://github.com/ezsystems/ezplatform-admin-ui/pull/1658
https://github.com/ezsystems/BehatBundle/pull/167
Adapted tests to the new approach.
1) Before merging remove the TMP commit
=> EZP-32175: Refactor & speed up tests 

src/bundle/Resources/views/themes/admin/system_info/info.html.twig
https://issues.ibexa.co/browse/IBX-836
=> IBX-836: Redesigned headers

src/bundle/Resources/views/themes/admin/system_info/composer.html.twig, src/bundle/Resources/views/themes/admin/system_info/symfony_kernel.html.twig
JIRA: https://issues.ibexa.co/browse/IBX-492
=> IBX-492: As an Editor, I want to see redesigned tables
